7 lib 14 disseny visual de la llibreria
annaruizverdaguer/llibreria-react pull request #8
Opened 2023-02-21 19:09 UTC by annarverdaguer

2023-03-01 08:46 UTC, Robertvera requested changes

2023-03-01 08:46 UTC, Robertvera commented on src/Llibreria.js
>                  Tristíssim, no tens llibres a l'estanteria :/
😂

2023-03-01 08:46 UTC, Robertvera commented on src/Form.css
> +form {
mmmm no acostuma a ser bona idea fer servir elements com a selectors

2023-03-01 08:46 UTC, Robertvera commented on src/Form.js
> +    <div className="form-container">
Fes una ullada a aquest estandard en quant a noms de classes --> https://getbem.com/

2023-03-01 08:46 UTC, Robertvera commented on src/Llibreria.js
>          let estanteriaActual = [...estanteria, props.llibre]
intenta posar tots els namings en anglés

2023-03-01 08:46 UTC, Robertvera commented on src/Llibreria.js
> +                    <hr/>
mmmm això ho podries fer millor per no repetir tant codi?

2023-03-15 10:15 UTC, Robertvera commented on src/Library.js
> +        let word = bookshelf.length !== 1 ? "llibres" : "llibre";
intenta fer servir sempre const a no ser que reassignis la variable en algun moment

2023-03-15 10:15 UTC, Robertvera commented on src/Library.js
> +                Tens <span className="text-highlight">{bookshelf.length}</span> {word} a l'estanteria!
podries fer rollo... `llibre{bookshelf.length !== 1 && 's'}` i t'estalvies la variable word?

2023-03-15 10:21 UTC, Robertvera commented on src/Library.js
> +    function printBookShelf() {
mmm no m'acaba de convencer aquest component. O sigui, el component hauria de retornar un template (html) i en base a l'estat del component canviar coses. Aquí estàs generant tot el template dinàmicament i fent servir un useEffect. Intenta pensar en quin html hauria de tornar aquest component quan hi hagi llibres i si no n'hi ha pensar en un empty state.

2023-03-18 12:18 UTC, annarverdaguer commented on src/Library.js
> +    function printBookShelf() {
he intentat el q em dius aqui: https://github.com/annaruizverdaguer/llibreria-react/tree/lib-14-now-approach-component-llibreria però ara el delete em funciona pitjor, sembla com q li falti un re-render després de borrar el llibre de la llista

2023-03-29 13:49 UTC, merged